name: 发布版本
on:
  push:
    tags:
      - 'V*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        sudo apt install zip unzip -y
        sudo npm install -g @vue/cli
        npm install
        bash ./release.sh

    - name: 上传发布包
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: ./_release/*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
